print("Why dont you play cards with cheetahs?")
input()
print("Because they always cheat")
input()
print("Why did the scarecrow win an award?")
input()
print("Because he was outstanding in his field!")
input()
print("Would you like to hear another joke")
answer = input()
if answer == "yes":
    print("What did the ocean say to the other ocean?")
    input()
    print("Nothing they just waved!")
    input()
    print("What do you call a pony with a cough?")
    input()
    print("A little horse!")